### ISSUE TITLE
Add mobile/desktop clients to identifier-configuration

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis-konnectd#19]
ownCloud mobile and desktop clients need to be added here:

https://github.com/owncloud/ocis-konnectd/blob/6543854f42a49b9124e113c5d1f3e57a593b92e5/assets/identifier-registration.yaml

@deepdiver can you please provide the required params or PR?

**Comment by DeepDiver1975** [comment]
feel free to grab from here: https://github.com/owncloud-docker/compose-playground/blob/546e95e471201c3e396893e8cf85ae64b7f5e2e2/kopano/konnect/konnectd-identifier-registration.yaml#L10-L26

**Comment by DeepDiver1975** [comment]
Taking care as I'm anyhow adding the graph explorer ...
