### ISSUE TITLE
integrate konnectd

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-konnectd#2]
- [x] actually start [Kopano konnect](https://github.com/Kopano-dev/konnect) when it is started as a go-micro service
- [ ] reuse the oidc handlers https://github.com/Kopano-dev/konnect/blob/master/oidc/provider/handlers.go or a more wholesome integration as a cmd: https://github.com/Kopano-dev/konnect/blob/master/cmd/konnectd/serve.go (corresponds to https://github.com/owncloud/ocis-hello/blob/master/pkg/command/server.go) ... or use NewServer entrypoint: https://github.com/Kopano-dev/konnect/blob/0b279e34969dbe162e322e10cd9ccb7d8067ba7c/server/server.go#L46
- [x] add konnect to our ports list: https://github.com/owncloud/ocis/wiki/Ports

**Comment by IljaN** [comment]
Make konnectd embedable https://github.com/Kopano-dev/konnect/issues/18

**Comment by DeepDiver1975** [comment]
refs https://github.com/Kopano-dev/konnect/pull/19
