### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis-konnectd#26]
After logging in and clicking the logout button in phoenix the following error appears on a white-page:
```400 invalid_request - id_token_hint does not match request```

**Comment by IljaN** [comment]
@DeepDiver1975 Do you have any lead on why this doesn't work?

**Comment by DeepDiver1975** [comment]
potential fix https://github.com/owncloud/phoenix/pull/2961

**Comment by micbar** [comment]
- needs Phoenix update

**Comment by micbar** [comment]
@IljaN @DeepDiver1975 This is not fixed by phoenix `v0.7.0`

We need to dig deeper.

**Comment by micbar** [comment]
Fixed with #61 and https://github.com/owncloud/phoenix/pull/3291

Needs new release for phoenix and ocis-konnectd
