### ISSUE TITLE
LDAP Groups not working with konnectd

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-konnectd#42]
Currently we cannot setup groups with LDAP while using konnectd.

I am groups with dn `cn=grp2,ou=TestGroups,dc=owncloud,dc=com`
and attributes `memberUid` on groups for the members

**Comment by DeepDiver1975** [comment]
Please elaborate. No Idea what you mean. THX

**Comment by dpakach** [comment]
@DeepDiver1975  I start ldap server with these variables
```
 -e LDAP_TLS_VERIFY_CLIENT=never
 -e LDAP_DOMAIN=owncloud.com \
 -e LDAP_ORGANISATION=ownCloud \
 -e LDAP_ADMIN_PASSWORD=admin \
```

And I use this ldif data to load users and groups
```
dn: ou=TestGroups,dc=owncloud,dc=com
objectclass: top
objectclass: organizationalUnit
ou: TestGroups

dn: ou=TestUsers,dc=owncloud,dc=com
objectclass: top
objectclass: organizationalUnit
ou: TestUsers

dn: cn=grp1,ou=TestGroups,dc=owncloud,dc=com
cn: grp1
gidnumber: 500
memberuid: user1
memberuid: user2
objectclass: top
objectclass: posixGroup

dn: uid=user1,ou=TestUsers,dc=owncloud,dc=com
cn: User1
sn: One
displayname: User One
gecos: User1
gidnumber: 5000
givenname: User1
homedirectory: /home/openldap/user1
loginshell: /bin/bash
mail: user1@example.org
objectclass: posixAccount
objectclass: inetOrgPerson
uid: user1
uidnumber: 30001
userpassword: 1234

dn: uid=user2,ou=TestUsers,dc=owncloud,dc=com
cn: User2
sn: Two
displayname: User Two
gecos: User2
gidnumber: 5000
givenname: User2
homedirectory: /home/openldap/user2
loginshell: /bin/bash
mail: user2@example.org
objectclass: posixAccount
objectclass: inetOrgPerson
uid: user2
uidnumber: 30002
userpassword: AaBb2Cc3Dd4
```

I run konnectd with this command
```
KONNECTD_ISS="https://172.17.0.1:9130" LDAP_BASEDN="dc=owncloud,dc=com" LDAP_BINDDN="cn=admin,dc=owncloud,dc=com" LDAP_URI=ldap://localhost:389 ocis-konnectd/bin/ocis-konnectd server
```

When I login to phoenix with konnectd as user `user1`, it shows `You are not part of any group`.
Since it works with oc10 + phoenix, I assumed this should work. Am I missing something here?

**Comment by DeepDiver1975** [comment]
Openid connect hast No understanding of groups. Make Sure the group ldap config is properly setup

**Comment by IljaN** [comment]
@dpakach Are you working against devldap or external ldap server?

**Comment by IljaN** [comment]
It looks to me as if the group has a different base dn then the users. 
>dn: cn=grp1,ou=TestGroups,dc=owncloud,dc=com
cn: grp1
gidnumber: 500
memberuid: user1
memberuid: user2
objectclass: top
objectclass: posixGroup

In owncloud ldap configuration check the Expert or Advanced tab, there you can provide a different base DN for groups which should be set to ```ou=TestGroups,dc=owncloud,dc=com```

**Comment by dpakach** [comment]
@IljaN, When I start konnectd I give env `LDAP_BASEDN="dc=owncloud,dc=com"`, and groups are inside `ou=TestGroups,dc=owncloud,dc=com` OU.
Souldn't it find the groups from that. Or do we have to give different base dn for user and groups. I don't understand. 

As for owncloud I provide `dc=owncloud,dc=com` as base dn for user and group both and it works.
Thanks

**Comment by IljaN** [comment]
> As for owncloud I provide dc=owncloud,dc=com as base dn for user and group both and it works.

@dpakach Might make sense. What kind of AD are you using? I have only experience with samba-ad. From my experience the default configuration creates both groups and users under cn=users.  Then you filter the groups based on the objectType=group.

Thus your basedn should be CN=Users,DC=owncloud,DC=com (though DC=owncloud,DC=com should also work). In your configuration it looks to me as if you have groups under an different ou.

If so you need to tell owncloud where to fetch the groups from (Advanced Tab) and set ```ou=TestGroups,dc=owncloud,dc=com``` as Group BaseDN there.

**Comment by IljaN** [comment]
@dpakach "Base Group Tree" => https://i.imgur.com/TC33ajN.png

**Comment by IljaN** [comment]
Any update on this?

**Comment by dpakach** [comment]
@IljaN I think we had a miscommunication on this one. I meant that the groups were not showing when using konnectd with **OCIS**, not using oc10. I'm not sure if that is available in ocis yet so I opened this issue. Is this supposed to work on OCIS?
If it is then I would appreciate any help you can provide. Thanks :+1:
